### ISSUE TITLE
Stable version numbering (ie 1.x.x)

### ISSUE THREAD

**Issue by charles-turner-1** [ACCESS-NRI/access-nri-intake-catalog#230]
I think we're probably at a point where we don't want to be altering the behaviour of the catalog in a way that will confuse users and/or change workflows substantially. 

To reflect this, should we consider updating our version number to a 1.x.x release to indicate that the library interface should be stable?

**Comment by marc-white** [comment]
I agree we're just about there, but I think there are a few things we need to get lined up before pulling that trigger. In particular:

- [ ] Finalize the catalog version numbering (#191 )
- [ ] Decide what to do about datasets that may be missing a `model` value (#223)
- [ ] Get `metadata-validate` to give a full report, not just the first failure (#216)
- [ ] Work out the frequency dates bug (#188)
- [ ] Confirm the Intake Take2 support/compatibility/upgrade (#153)

Any others?

**Comment by charles-turner-1** [comment]
I think that would be a good target in terms of features. I think we could potentially also think about adding translators for the datasets with open data requests (as of today) - this process is generally pretty straightforward & fast.

- [ ] #214 
- [ ] #202
- [ ] #198 
- [ ] #197 
- [ ] #196

**Comment by rbeucher** [comment]
I agree. Let's do that and we can make a stable release.

**Comment by charles-turner-1** [comment]
I've edited the features list to add a two parter for Take2 - I'm going to leave #153 open until we've got an E2E build test on a catalog subset.

**Comment by charles-turner-1** [comment]
@rbeucher @marc-white Did we decide last week to leave #188 out of this release?

**Comment by rbeucher** [comment]
Yes, pb for later :-)

**Comment by charles-turner-1** [comment]
> I agree we're just about there, but I think there are a few things we need to get lined up before pulling that trigger. In particular:
> 
> * * [x] 
>     [x]  Decide what to do about datasets that may be missing a `model` value ([[BUG] Make `model` required for `metadata.yaml` files #223](https://github.com/ACCESS-NRI/access-nri-intake-catalog/issues/223))* [x] 
>     [x]  Confirm the Intake Take2 support/compatibility/upgrade ([Intake Take2 #153](https://github.com/ACCESS-NRI/access-nri-intake-catalog/issues/153))* [x] 
>     [x]  Finalize the catalog version numbering ([Default to a "latest" version? #191](https://github.com/ACCESS-NRI/access-nri-intake-catalog/issues/191) )* [x] 
>     [x]  Get `metadata-validate` to give a full report, not just the first failure ([Make `metadata-validate` provide a full report on first pass #216](https://github.com/ACCESS-NRI/access-nri-intake-catalog/issues/216))* [x] 
>     [x]  Support for Intake Take2 [Intake Take2 #233](https://github.com/ACCESS-NRI/access-nri-intake-catalog/pull/233) &* // Deferred [ ] Work out the frequency dates bug ([The frequency in the intake catalog does not account for snapshot data #188](https://github.com/ACCESS-NRI/access-nri-intake-catalog/issues/188))
>     Any others?

We've ticked these all off, so unless there are any more issues that we think are crucial to get fixed, I think we can get ready for a release chaps @rbeucher @marc-white.

**Comment by rbeucher** [comment]
We have a new request on the Hive:
ROMS Ice Shelf Request.
https://forum.access-hive.org.au/t/roms-iceshelf/3931?u=rbeucher

@AndyHoggANU also asked me yesterday during TL how much effort this would involve.

Currently, they are still deciding where to store the data. My suggestion is that we proceed with a release as planned and then start incorporating the Intake-ESM data stores from NCI.

Once the location of the ROMS data is confirmed, we can explore adding it to the catalog.
@marc-white

**Comment by rbeucher** [comment]
One thing that would be good to have is an updated version of the instructions on requesting data to be added to the catalog.

**Comment by marc-white** [comment]
Pretty sure that's already been done? I just built the documentation from `main`, it seems to be all updated w.r.t. the new catalog structure.

**Comment by rbeucher** [comment]
We need to ensure that any references to or dependencies on hh5 are removed. With CLEX shutting down, hh5 will no longer be updated after December. Could you please verify that the documentation does not mention hh5?

**Comment by rbeucher** [comment]
Considering we are taking over analysis3.
Maybe we should use the mirrored copy I have in xp65.

**Comment by marc-white** [comment]
I tried to load up analysis3 via xp65 in an ARE session, but there seems to be an issue:

```term
Script starting...
Waiting for Jupyter Notebook server to open port 62931...
TIMING - Starting wait at: Wed Nov 27 16:55:13 AEDT 2024
TIMING - Starting main script at: Wed Nov 27 16:55:13 AEDT 2024
Loading conda/analysis3-24.07
  Loading requirement: singularity
/g/data/xp65/public/apps/med_conda_scripts/analysis3-24.07.d/bin/jupyter
/g/data/xp65/public/apps/med_conda_scripts/analysis3-24.07.d/bin/jupyter
TIMING - Starting jupyter at: Wed Nov 27 16:55:14 AEDT 2024
+ ssh-agent -- jupyter lab --config=/home/120/mcw120/ondemand/data/sys/dashboard/batch_connect/sys/jupyter/ncigadi/output/70084362-b188-48ed-b450-656c0efaafe3/config.py --FileContentsManager.root_dir=/home/120/mcw120/.jupyter-root
[I 2024-11-27 16:55:24.067 ServerApp] dask_labextension | extension was successfully linked.
[I 2024-11-27 16:55:24.067 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-11-27 16:55:24.067 ServerApp] jupyter_resource_usage | extension was successfully linked.
[I 2024-11-27 16:55:24.074 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2024-11-27 16:55:24.074 ServerApp] jupyter_server_proxy | extension was successfully linked.
[I 2024-11-27 16:55:24.079 ServerApp] jupyter_server_terminals | extension was successfully linked.
[W 2024-11-27 16:55:24.083 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-11-27 16:55:24.083 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-11-27 16:55:24.083 LabApp] 'port_retries' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-11-27 16:55:24.083 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-11-27 16:55:24.083 LabApp] 'base_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-11-27 16:55:24.084 LabApp] 'base_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-11-27 16:55:24.084 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-11-27 16:55:24.084 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-11-27 16:55:24.084 LabApp] 'disable_check_xsrf' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-11-27 16:55:24.086 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[W 2024-11-27 16:55:24.086 ServerApp] notebook_dir is deprecated, use root_dir
[I 2024-11-27 16:55:24.086 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-11-27 16:55:24.086 ServerApp] nbdime | extension was successfully linked.
[I 2024-11-27 16:55:24.092 ServerApp] notebook | extension was successfully linked.
[I 2024-11-27 16:55:24.633 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-11-27 16:55:24.634 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
Traceback (most recent call last):
  File "/g/data/xp65/public/apps/med_conda/envs/analysis3-24.07/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/g/data/xp65/public/apps/med_conda/envs/analysis3-24.07/lib/python3.11/site-packages/jupyter_server/extension/application.py", line 616, in launch_instance
    serverapp = cls.initialize_server(argv=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g/data/xp65/public/apps/med_conda/envs/analysis3-24.07/lib/python3.11/site-packages/jupyter_server/extension/application.py", line 586, in initialize_server
    serverapp.initialize(
  File "/g/data/xp65/public/apps/med_conda/envs/analysis3-24.07/lib/python3.11/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g/data/xp65/public/apps/med_conda/envs/analysis3-24.07/lib/python3.11/site-packages/jupyter_server/serverapp.py", line 2755, in initialize
    self.init_configurables()
  File "/g/data/xp65/public/apps/med_conda/envs/analysis3-24.07/lib/python3.11/site-packages/jupyter_server/serverapp.py", line 2058, in init_configurables
    self.kernel_spec_manager = self.kernel_spec_manager_class(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g/data/xp65/public/apps/med_conda/envs/analysis3-24.07/lib/python3.11/site-packages/nb_conda_kernels/manager.py", line 127, in __init__
    "nb_conda_kernels | enabled, %s kernels found.", len(self._conda_kspecs)
                                                         ^^^^^^^^^^^^^^^^^^
  File "/g/data/xp65/public/apps/med_conda/envs/analysis3-24.07/lib/python3.11/site-packages/nb_conda_kernels/manager.py", line 389, in _conda_kspecs
    for name, info in self._all_specs().items():
                      ^^^^^^^^^^^^^^^^^
  File "/g/data/xp65/public/apps/med_conda/envs/analysis3-24.07/lib/python3.11/site-packages/nb_conda_kernels/manager.py", line 267, in _all_specs
    conda_prefix = self._conda_info['conda_prefix']
                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'conda_prefix'
+ die 'ERROR: Jupyter Lab exited with non-zero code (1)'
+ MSG='ERROR: Jupyter Lab exited with non-zero code (1)'
+ '[' '!' -z 'ERROR: Jupyter Lab exited with non-zero code (1)' ']'
+ echo '<div class="error-msg">ERROR: Jupyter Lab exited with non-zero code (1)</div>'
+ kill -9 4009395
-/bin/bash: line 1: 4009395 Killed                  /local/spool/pbs/mom_priv/jobs/129602447.gadi-pbs.SC
++ date
+ echo 'TIMING - Finished jupyter at: Wed Nov 27 16:55:27 AEDT 2024'
TIMING - Finished jupyter at: Wed Nov 27 16:55:27 AEDT 2024

======================================================================================
                  Resource Usage on 2024-11-27 16:55:30:
   Job Id:             129602447.gadi-pbs
   Project:            tm70
   Exit Status:        137 (Linux Signal 9 SIGKILL Kill, unblockable)
   Service Units:      0.17
   NCPUs Requested:    28                     NCPUs Used: 28              
                                           CPU Time Used: 00:00:07        
   Memory Requested:   126.0GB               Memory Used: 535.82MB        
   Walltime requested: 01:00:00            Walltime Used: 00:00:17        
   JobFS requested:    100.0MB                JobFS used: 0B              
======================================================================================
```

**Comment by rbeucher** [comment]
I just tried. It works fine for me

`![Image](https://github.com/user-attachments/assets/820740ee-8bf0-4216-9ad5-aa85853b882d)

**Comment by marc-white** [comment]
That was my setup as well, still getting the same issue. Will come back to it again tomorrow.

**Comment by marc-white** [comment]
OK that environment is now suddenly working for me this morning, must have been a ghost in the machine. Cracking on with updating the notebooks...

**Comment by marc-white** [comment]
Oops, spoke to soon. Putting `conda/analysis3` in as "Modules" starts up OK, but doesn't give me the right Jupyter kernel (just the system Python3 one). Putting in `conda/analysis3-24.07` gives the same error I got yesterday:
![Image](https://github.com/user-attachments/assets/3b18b300-6a72-4397-8088-ee017cf10f79)
![Image](https://github.com/user-attachments/assets/7bf47a79-ef1d-4a68-b103-ca8181a608d3)

**Comment by rbeucher** [comment]
OK I am looking into it

**Comment by rbeucher** [comment]
Hi @marc-white, @charles-turner-1,  

I’ve successfully updated and fixed the conda environment. The new environment is named `conda/analysis3-24.12`.  

### Key differences from the current `hh5` environment:  
- **Upgraded Python**: Now using Python >= 3.11.  
- **Removed packages**:  
  - `cdms2`  
  - `intake-thredds`  
- **Cleaned up Jupyter Lab extensions**: Removed some problematic or unnecessary extensions.  

Please give it a try and let me know how it performs or if you encounter any issues.

**Comment by charles-turner-1** [comment]
Just noting the issue requiring `openmpi` to be loaded as a module separately when using `conda/analysis3-24.12` here.

I don't think this should affect the release at all (although we might need to rebuild the environment after the release with the updated version of this package), so I think we're ready to publish the release now?

@marc-white @rbeucher

**Comment by charles-turner-1** [comment]
Marking this as completed.
